  version: '3.8'

  services:
    db:
      image: postgres
      restart: always

      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres

      volumes:
          - postgres_data:/var/lib/postgresql/data
      networks:
        - djangonetwork
    web:
      build:  .
      container_name: web
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./app/:/usr/src/app

      ports:
        - "8000:8000"
      depends_on:
        - db
      links:
        - db:db
      networks:
        - djangonetwork
  volumes:
    postgres_data:
  networks:
    djangonetwork:
      driver: bridge
