# Generated by Django 3.1.4 on 2020-12-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('fonction', models.CharField(choices=[('Enseignant', 'Enseignant'), ('Surveillant', 'Surveillant'), ('Censeur', 'Censeur'), ('Proviseur', 'Proviseur')], max_length=50)),
            ],
        ),
    ]
