# Generated by Django 3.1.4 on 2020-12-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_censeur_censeurmanager_enseignant_enseignantmanager_proviseur_proviseurmanager_surveillant_surveilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
