# Generated by Django 3.1.4 on 2020-12-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=20)),
                ('nbre_places', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('datenaiss', models.DateTimeField(verbose_name='date de naissance:')),
                ('lieunaiss', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=20)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.classe')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.parent')),
            ],
        ),
    ]
