# Generated by Django 3.1.4 on 2021-02-07 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210113_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais_scolarite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_scolarite', models.BigIntegerField(default=0)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Tranche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('montant_tranche', models.BigIntegerField(default=0)),
                ('totalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.frais_scolarite')),
            ],
        ),
    ]
