# Generated by Django 3.1.4 on 2021-02-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_auto_20210113_0303'),
        ('staff', '0003_auto_20201222_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('eleve', models.ManyToManyField(to='registration.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('coef', models.IntegerField(default=2)),
                ('classe', models.ManyToManyField(to='registration.Classe')),
                ('enseignant', models.ManyToManyField(to='staff.Enseignant')),
                ('note', models.ManyToManyField(to='report_card.Note')),
            ],
        ),
    ]
