# Generated by Django 3.1.4 on 2021-02-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='valeur',
            new_name='evaluation2',
        ),
        migrations.AddField(
            model_name='note',
            name='evaluation1',
            field=models.FloatField(default=0),
        ),
    ]
