# Generated by Django 3.1.4 on 2021-02-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0002_auto_20210205_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='evaluation2',
            field=models.FloatField(default=0),
        ),
    ]
