# Generated by Django 3.1.4 on 2021-02-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0003_auto_20210205_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='discipline',
            field=models.ManyToManyField(to='report_card.Discipline'),
        ),
    ]
