# Generated by Django 3.1.4 on 2021-02-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0004_auto_20210205_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=50)),
                ('annee', models.CharField(default=9999, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='examen',
            field=models.ForeignKey(default=2021, on_delete=django.db.models.deletion.CASCADE, to='report_card.examen'),
            preserve_default=False,
        ),
    ]
