# Generated by Django 3.1.4 on 2021-02-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0005_auto_20210205_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='annee',
            field=models.CharField(max_length=30),
        ),
    ]
