# Generated by Django 3.1.4 on 2021-02-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0006_auto_20210205_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='examen',
        ),
    ]
