# Generated by Django 3.1.4 on 2021-02-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0009_examen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examen',
            new_name='Evaluation',
        ),
    ]
