# Generated by Django 3.1.4 on 2021-02-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0013_note_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='evaluation',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
