# Generated by Django 3.1.4 on 2021-02-07 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0015_composition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Composition',
            new_name='Examens',
        ),
    ]
