# Generated by Django 3.1.4 on 2021-02-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0016_auto_20210207_0406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Examens',
        ),
    ]
