# Generated by Django 3.1.4 on 2021-02-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0017_delete_examens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(max_length=50)),
                ('annee', models.CharField(max_length=30)),
            ],
        ),
    ]
