# Generated by Django 3.1.4 on 2021-02-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_card', '0019_auto_20210210_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='examen',
        ),
    ]
